### ISSUE TITLE
problem: missing read template file

### ISSUE THREAD

**Issue by turbogeek** [twitter/hogan.js#207]
I am getting a 'missing read template file' error. The file exists (and all names match), but it seems that the app is not loading the page. Is this an issue with the compiler cache? If so, how do I delete the cache?

missing read template file : /Users/theuserdir/GitHub/Esignature/views/medical_consult_report_review_page.hjs

Error: missing read template file : /Users/theuserdir/GitHub/Esignature/views/medical_consult_report_review_page.hjs
    at Object.Hogan.fcompile (/Users/theuserdir/GitHub/Esignature/node_modules/hjs/lib/express.js:48:10)
    at View.Hogan.renderFile [as engine](/Users/theuserdir/GitHub/Esignature/node_modules/hjs/lib/express.js:76:19)
    at View.render (/Users/theuserdir/GitHub/Esignature/node_modules/express/lib/view.js:76:8)
    at Function.app.render (/Users/theuserdir/GitHub/Esignature/node_modules/express/lib/application.js:503:10)
    at ServerResponse.res.render (/Users/theuserdir/GitHub/Esignature/node_modules/express/lib/response.js:802:7)
    at /Users/theuserdir/GitHub/Esignature/routes/medical_consult_report_review_page.js:14:13
    at /Users/theuserdir/GitHub/Esignature/get_consult.js:148:21
    at Parser.<anonymous> (/Users/theuserdir/GitHub/Esignature/node_modules/xml2js/lib/xml2js.js:384:20)
    at Parser.emit (events.js:95:17)
    at Object.onclosetag (/Users/theuserdir/GitHub/Esignature/node_modules/xml2js/lib/xml2js.js:348:26)

**Comment by agnivade** [comment]
Hey @turbogeek - I am having the same error. I am not sure what the bad piece of template is. Can you tell what was your issue ? I am new to hoganjs and express.
